---
title: "glm_results"
output: html_document
---

```{r setup}
setwd("/home/megan/frequentist-bayesian-p-values-/logistic regression")
#set up 
library(brms)
library(rstanarm)
library(bayestestR)
library(BayesFactor)
library(cmdstanr)
library(emmeans)
library(parallel)
library(bridgesampling)
library(tidyverse)
library(extraDistr)
options(contrasts=c('contr.equalprior_deviations', 'contr.poly'))
options(brms.backend = "rstan")
library("extraDistr")
library(lme4)
library(binom)
```

```{r}
group2n1000 <- bind_rows(glmresults_2groups, .id = "id")
group3n951 <- bind_rows(glmresults_3groups, .id = "id")

group2nExtra <- bind_rows(glmresults_2groups, .id = "id")
group3nExtra <- bind_rows(glmresults_3groups, .id = "id")


glmresults_2groups <- bind_rows(glmresults_2groups_998, glmresults_2groups_Extra, .id = "id")
group2n1000

group2 <- bind_rows(group2n20, group2n30, group2n50, group2n100, group2n1000)
group3 <- bind_rows(group3n20, group3n30, group3n50, group3n100, group3n1000)

glmresults_2groups$id <- as.numeric(glmresults_2groups$id)
group2n1000 <- glmresults_2groups %>% filter(id <= 1000)

group2n1000 <- group2n1000 %>% rename(samplesize = n)
group3n1000$id <- as.character(group3n1000$id)
group2GLM <- bind_rows(group2GLM, group2n1000)


rm(g20, glmresults_3groups)

save(group2n1000, file = "glm_2groups_n1000_iter1000.rda")
save(group2, file = "glm_2GROUP.rda")
save(group3, file = "glm_3GROUP.rda")


group2$group <- 2
group3$group <- 3

glm <- bind_rows(group2, group3)
save(glm, file = "glm_results.rda")
```

#tests 
```{r}
alpha <- 0.05 #set threshold for significance 

glm <- glm %>% 
  mutate(psig = if_else(pval < alpha, "sig", "nonsig"), 
         psig_df = if_else(pval_df < alpha, "sig", "nonsig")) #p<.05 --> rej null TRUE, do not rej FALSE

#bayes factors 
glm <- glm %>% 
  mutate(bf_comb = if_else(exp(bf) < 1/3, "alt", if_else(exp(bf) > 3, "null", "no")))

glm <- glm %>% rename(type = test, samplesize = n)
```


#run from here for results 
```{r}
load("glm_2groupresults.rda")
load("glm_3groupresults.rda")
load("glm_results.rda")
```

#plot of raw results 
```{r}
#wald p value 
group2GLM$type_f = factor(group2GLM$type, levels=c('freq','bayes_flatprior','bayes_tighterprior', 'bayes_widerprior'))
plot_pval2 <- group2GLM %>% mutate(samplesize = paste0("n = ", samplesize), 
                                   type_f = recode(type_f, "freq" = "Frequentist", 
                                                   "bayes_flatprior" = "Flat Prior",
                                                   "bayes_widerprior" = "Wider Prior", 
                                                   "bayes_tighterprior" = "Tighter Prior") )
plot_pval2$samplesize = factor(plot_pval2$samplesize, levels=c('n = 20','n = 30','n = 50','n = 100', 'n = 1000'))

group3GLM$type_f = factor(group3GLM$type, levels=c('freq','bayes_flatprior','bayes_tighterprior', 'bayes_widerprior'))
plot_pval3 <- group3GLM %>% mutate(samplesize = paste0("n = ", samplesize), 
                                   type_f = recode(type_f, "freq" = "Frequentist", 
                                                   "bayes_flatprior" = "Flat Prior",
                                                   "bayes_widerprior" = "Wider Prior", 
                                                   "bayes_tighterprior" = "Tighter Prior") )
plot_pval3$samplesize = factor(plot_pval3$samplesize, levels=c('n = 20','n = 30','n = 50','n = 100', 'n = 1000'))
```

#PVALUES 
```{r}
#p value 
ggplot(plot_pval2, aes(x = pval)) + 
  geom_histogram(aes(y = after_stat(density)), binwidth = .05, boundary = 0) + 
  facet_grid(type_f ~ samplesize, labeller = labeller(type_f = label_wrap_gen(10)))  + 
  geom_vline(xintercept = .05, colour = "blue", linetype = 2) + 
  ylab("Density") +
  xlab("p-values") + 
  labs(title = "glm 2 group p val")
ggsave("glm_2group_pvalRAW.png", width = 30, height = 20, units = "cm")

#p value 
ggplot(plot_pval3, aes(x = pval)) + 
  geom_histogram(aes(y = after_stat(density)), binwidth = .05, boundary = 0) + 
  facet_grid(type_f ~ samplesize, labeller = labeller(type_f = label_wrap_gen(10)))  + 
  geom_vline(xintercept = .05, colour = "blue", linetype = 2) + 
  ylab("Density") +
  xlab("p-values") + 
  labs(title = "glm 3 group p val")
ggsave("glm_3group_pvalRAW.png", width = 30, height = 20, units = "cm")
```
## BFS
```{r}
plot_bf2 <- plot_pval2 %>% filter(type != "freq")

ggplot(plot_bf2, aes(x = bf)) + 
  geom_histogram(aes(y = after_stat(density)), binwidth = .05, boundary = 0) + 
  facet_grid(type_f ~ samplesize, labeller = labeller(type_f = label_wrap_gen(15)))  + 
  geom_vline(xintercept = 0, colour = "blue", linetype = 2)  + 
  ylab("Density") +
  xlab("Bayes Factors (Exponential)")  + 
  labs(title = "glm 2 group bf")
ggsave("glm_2group_bfRAW.png", width = 30, height = 20, units = "cm")


plot_bf3 <- plot_pval3 %>% filter(type != "freq")

ggplot(plot_bf3, aes(x = bf))  + 
  geom_histogram(aes(y = after_stat(density)), binwidth = .05, boundary = 0) + 
  facet_grid(type_f ~ samplesize, labeller = labeller(type_f = label_wrap_gen(10)))  + 
  geom_vline(xintercept = 0, colour = "blue", linetype = 2)  + 
  ylab("Density") +
  xlab("Bayes Factors (Exponential)") + 
  labs(title = "glm 3 group bf")
ggsave("glm_3group_bfRAW.png", width = 30, height = 20, units = "cm")
```

#CIS
```{r}
iter = 1000
wald <- glm %>% 
  group_by(group, samplesize, type) %>% 
  count(psig) %>% 
  pivot_wider(names_from = "psig", values_from = "n") %>% 
  rename(x = sig, 
         non = nonsig) 
wald$x[is.na(wald$x)] <- 0

wald_df <- glm %>% 
  group_by(group, samplesize, type) %>% 
  count(psig_df) %>% 
  pivot_wider(names_from = "psig_df", values_from = "n") %>% 
  rename(x = sig, 
         non = nonsig) 
wald_df$x[is.na(wald_df$x)] <- 0
```

#confidence intervals
```{r}
wald$ci <- binom.bayes(wald$x, 1000, conf.level = 0.95)
wald$test <- "pval"


wald_df$ci <- binom.bayes(wald_df$x, 1000, conf.level = 0.95)
wald_df$test <- "pval"
```


#make one big plot of cis 
##2group 
```{r}

wald$type_f = factor(wald$type, levels=c('freq','bayes_flatprior','bayes_tighterprior','bayes_studentprior', "bayes_widerprior"))
wald <- wald %>% mutate(type_f = recode(type_f, "freq" = "Frequentist", 
                                                      "bayes_flatprior" = "Flat Prior",
                                                      "bayes_widerprior" = "Wider Prior", 
                                                      "bayes_tighterprior" = "Tighter Prior"), 
                      test = recode(test, "pval" = "p-values", "bf" = "Bayes Factors")) 

wald_df$type_f = factor(wald_df$type, levels=c('freq','bayes_flatprior','bayes_tighterprior','bayes_studentprior', "bayes_widerprior"))
wald_df <- wald_df %>% mutate(type_f = recode(type_f, "freq" = "Frequentist", 
                                                      "bayes_flatprior" = "Flat Prior",
                                                      "bayes_widerprior" = "Wider Prior", 
                                                      "bayes_tighterprior" = "Tighter Prior"), 
                      test = recode(test, "pval" = "p-values", "bf" = "Bayes Factors")) 

```

```{r}

ggplot(wald, aes(x = as.factor(samplesize), y = ci$mean, group = 1)) + 
  geom_line() + 
  geom_point(size = .2) + 
  geom_errorbar(aes(ymin = ci$lower, ymax = ci$upper), width = 0.01, colour = "blue") + 
  facet_grid(group ~ type_f) + 
  geom_hline( aes(yintercept = .05), colour = "blue", linetype = "dotted") + 
  ylab("Type I Error Rate") +
  scale_y_continuous(limits = c(0, 0.5)) + 
  xlab("Sample Size") + 
  labs(title = "glm pval CI ") + 
  theme_bw() +   
  theme(axis.line.y = element_blank(), axis.line.x = element_line(size=.1, colour = "grey"), 
        axis.title = element_text(face="bold"),
        panel.grid.major.x = element_line(size=.1, colour = "grey"), 
        panel.grid.major.y = element_line(size=.1, color="grey"),
        legend.position = c(0.2, 0.8), 
        legend.title = element_blank(),
        plot.title = element_text(size = 9))

ggsave("glm_pval_CI.png")

ggplot(wald_df, aes(x = as.factor(samplesize), y = ci$mean, group = 1)) + 
  geom_line() + 
  geom_point(size = .2) + 
  geom_errorbar(aes(ymin = ci$lower, ymax = ci$upper), width = 0.01, colour = "blue") + 
  facet_grid(group ~ type_f) + 
  geom_hline( aes(yintercept = .05), colour = "blue", linetype = "dotted") + 
  ylab("Type I Error Rate") +
  scale_y_continuous(limits = c(0, 0.5)) + 
  xlab("Sample Size") + 
  labs(title = "glm pval CI DF") + 
  theme_bw() +   
  theme(axis.line.y = element_blank(), axis.line.x = element_line(size=.1, colour = "grey"), 
        axis.title = element_text(face="bold"),
        panel.grid.major.x = element_line(size=.1, colour = "grey"), 
        panel.grid.major.y = element_line(size=.1, color="grey"),
        legend.position = c(0.2, 0.8), 
        legend.title = element_blank(),
        plot.title = element_text(size = 9))


ggsave("glm_pval_CI_DF.png")

```
```{r}
wald = wald %>% mutate(group = recode(group, "2" = "2 group",  "3" = "3 group"), 
                       samplesize = as.factor(samplesize))
ggplot(wald, aes(x = samplesize, y = ci$mean, group = type_f, colour = type_f)) + 
  geom_line(size = 1.5) + 
  geom_point(size = .2) + 
  geom_errorbar(aes(ymin = ci$lower, ymax = ci$upper), width = 0.01, size = 1.5) + 
  facet_wrap(vars(group)) + 
  geom_hline( aes(yintercept = .05), colour = "blue", linetype = "dotted") + 
  ylab("Type I Error Rate") +
  scale_y_continuous(limits = c(0, 0.15)) + 
  xlab("Sample Size") + 
  labs(title = "glm pval CI ", colour = "Model type") + 
  theme_bw() +   
  theme(axis.line.y = element_blank(), axis.line.x = element_line(size=.1, colour = "grey"),
        axis.text = element_text(size = 15),
        axis.title = element_text(face="bold", size = 15),
        panel.grid.major.x = element_line(size=.1, colour = "grey"), 
        panel.grid.major.y = element_line(size=.1, color="grey"),
        plot.title = element_text(size = 9), 
        legend.position = c(0.35, 0.75),
        legend.text = element_text(size = 10),
          strip.text.x = element_text(size = 14)) 
ggsave("glm_pval_CI_poster.png")
```
#check nominality 
```{r}
pval <- wald %>% group_by(type_f, samplesize, group) %>% 
  summarise(nominal = if_else(ci$lower < .05 & ci$upper > .05, 1, 0),
            aboveNominal = if_else(ci$lower > .05 & ci$upper > .05, 1, 0),
            belowNominal = if_else(ci$lower < .05 & ci$upper < .05, 1, 0))
pval$rate <- ci_pval$ci$mean

pval_df <- wald_df %>% group_by(type_f, samplesize, group) %>% 
  summarise(nominal = if_else(ci$lower < .05 & ci$upper > .05, 1, 0),
            aboveNominal = if_else(ci$lower > .05 & ci$upper > .05, 1, 0),
            belowNominal = if_else(ci$lower < .05 & ci$upper < .05, 1, 0))
pval$rate <- ci_pval$ci$mean
#group by type, then check if lower < .05 and upper > .05 -->1 
```

#bayes factor area plot 
```{r}
group2GLM$group = 2
group3GLM$group = 3

data <- bind_rows(group2GLM, group3GLM)
data <- data %>% filter(type != "freq" & type != "bayes_flatprior") %>% 
  group_by(group, samplesize, type_f) %>%
  count(bf_comb) %>%
  mutate(percentage = n / sum(n))
data <- data %>% mutate(bf_comb = recode(bf_comb, "alt" = "Evidence for the Alternative", "no" = "Ambiguous Evidence", "null" = "Evidence for the Null"))

group2NULL <- data %>% filter(group == 2, samplesize < 1000) %>% 
  filter(samplesize != 100 | type_f != "bayes_widerprior") %>% 
  filter(bf_comb == "Evidence for the Alternative") %>% 
  mutate(bf_comb = "Evidence for the Null", n = 0, percentage = 0)
data <- rbind(data, group2NULL)
group3NULL <- data %>% filter(group == 3) %>% 
  filter(samplesize <= 50, type_f == "bayes_tighterprior") %>% 
  filter(bf_comb == "Evidence for the Alternative") %>% 
  mutate(bf_comb = "Evidence for the Null", n = 0, percentage = 0)
data <- rbind(data, group3NULL)

data <- data %>% group_by(samplesize, type_f) %>% 
  mutate(sum = sum(percentage))

data <- data %>% mutate(log_ss = log(samplesize), 
                        log10_ss = log10(samplesize), 
                        log2_ss = log2(samplesize), 
                        fake_ss = samplesize) %>% 
  mutate(fake_ss = dplyr::recode(fake_ss, "50" = 40, "100" = 50, "1000" = 60))

data$bf_comb = factor(data$bf_comb, levels=c("Evidence for the Null", "Ambiguous Evidence","Evidence for the Alternative"))
data$group_f = data$group 
data <- data %>% mutate(group_f = recode(group_f, "2" = "2 group", "3" = "3 group"))
data$type_r = data$type_f 
data <- data %>% mutate(type_r = recode(type_r,  "bayes_widerprior" = "Wider Prior", "bayes_tighterprior" = "Tighter Prior"))

ggplot(data, aes(x = fake_ss, y = percentage, fill = bf_comb)) + 
   geom_area(colour = "black", alpha = 0.6) + facet_grid(group_f ~ type_r) + 
  theme_bw() + 
  ylab("Proportion of Bayes Factors")  + 
  xlab("Sample Size") + 
  labs(title = "glm bf") + 
  theme_bw() +   
  theme(axis.line.y = element_blank(), 
        axis.title = element_text(face="bold"),
        panel.grid.major.x = element_line(size=.1, colour = "grey"), 
        panel.grid.major.y = element_line(size=.1, color="grey"),
        plot.title = element_text(size = 9), 
        legend.key.size = unit(0.4, 'cm'), 
        legend.key.height = unit(0.3, 'cm'), #change legend key height
        legend.key.width = unit(0.3, 'cm'), #change legend key width
        legend.text = element_text(size=7), 
        legend.position = c(0.155, 0.85)) + #change legend text font size 
  scale_x_continuous(breaks = c(20, 30, 40, 50, 60), labels = c(20, 30, 50, 100, 1000)) + 
  guides(fill = guide_legend(title = NULL)) + scale_fill_manual(values = c("#E69F00", "#56B4E9", 
    "#CC79A7"))


ggsave("glm_bf.png")
```
