---
title: "simple linear regression analysis"
output: html_document
---

```{r setup, include=FALSE}
library(brms)
library(rstanarm)
library(bayestestR)
library(BayesFactor)
library(cmdstanr)
library(emmeans)
library(parallel)
library(bridgesampling)
library(tidyverse)
library(extraDistr)
library(binom)
```

```{r}
#read in results 
tighter3_n100 <- bind_rows(results_3groups, .id = "id")

rm(tighter3_n20, tighter3_n50, tighter3_n30, tighter3_n100)
save(final_twogroups, file = "simulation_2group.rda")
save(final_threegroups, file = "simulation_3group.rda")
```

```{r}
tighttwogroups <- bind_rows(tighter2_n20, tighter2_n30, tighter2_n50, tighter2_n100)
tightthreegroups <- bind_rows(tighter3_n20, tighter3_n50, tighter3_n30, tighter3_n100)

final_twogroups <- bind_rows(twogroups, tighttwogroups)
final_threegroups <- bind_rows(threegroups, tightthreegroups)
```
#tests 
```{r}
alpha <- 0.05 #set threshold for significance 
#pvalues
final_twogroups <- final_twogroups %>% 
  mutate(wald_significance = if_else(pval < alpha, "sig", "nonsig"), 
         likelihood_sig = if_else(p_likelihood < alpha, "sig", "nonsig"), 
         likelihood_max_sig = if_else(p_likelihood_max < alpha, "sig", "nonsig")) #p<.05 --> rej null TRUE, do not rej FALSE

final_threegroups <- final_threegroups %>% 
  mutate(wald_significance = if_else(pval < alpha, "sig", "nonsig"), 
         likelihood_sig = if_else(p_likelihood < alpha, "sig", "nonsig"), 
         likelihood_max_sig = if_else(p_likelihood_max < alpha, "sig", "nonsig")) #p<.05 --> rej null TRUE, do not rej FALSE

#bayes factors 
final_twogroups <- final_twogroups %>% mutate(bf_prop = if_else(exp(bf) > 3, "null", "no"))
final_threegroups <- final_threegroups %>% mutate(bf_prop = if_else(exp(bf) > 3, "null", "no"))
exp(0.57763990)

#loo & waic 
final_twogroups <- final_twogroups %>% mutate(
  loo_results = if_else(abs(loo_diff) > abs(2*loo_se),"yes", "no"),
  waic_results = if_else(abs(waic_diff) > abs(2*waic_se), "yes", "no")
) %>% 
  rename(samplesize = n)

final_threegroups <- final_threegroups %>% mutate(
  loo_results = if_else(abs(loo_diff) > abs(2*loo_se),"yes", "no"),
  waic_results = if_else(abs(waic_diff) > abs(2*waic_se), "yes", "no")
) %>% 
  rename(samplesize = n)
save(final_threegroups, file = "simulation_3groupFINAL.rda")
```

#run from here for results 
```{r}
load("simulation_2groupFINAL.rda")
load("simulation_3groupFINAL.rda")
```

```{r}
iter = 1000
wald_2group <- final_twogroups %>% 
  group_by(samplesize, type) %>% 
  count(wald_significance) %>% 
  pivot_wider(names_from = "wald_significance", values_from = "n") %>% 
  mutate(rate_typeIerr = sig/iter) %>% 
  rename(x = sig) 

wald_3group <- final_threegroups %>% 
  group_by(samplesize, type) %>% 
  count(wald_significance)%>% 
  pivot_wider(names_from = "wald_significance", values_from = "n") %>% 
  mutate(rate_typeIerr = sig/iter) %>% rename(x = sig)

bf_2group <- final_twogroups %>% 
  group_by(samplesize, type) %>% 
  count(bf_prop) %>% 
  filter(type != "freq") %>% 
  pivot_wider(names_from = "bf_prop", values_from = "n") %>% 
  mutate(rate_null = null/iter) %>% rename(x = null)
bf_2group$x[is.na(bf_2group$x)] <- 0
bf_2group$rate_null[is.na(bf_2group$rate_null)] <- 0

bf_3group <- final_threegroups %>% 
  group_by(samplesize, type) %>% 
  count(bf_prop) %>% 
  filter(type != "freq") %>% 
  pivot_wider(names_from = "bf_prop", values_from = "n")  %>% 
  mutate(rate_null = null/iter) %>% rename(x = null)
bf_3group$x[is.na(bf_3group$x)] <- 0
bf_3group$rate_null[is.na(bf_3group$rate_null)] <- 0

loo_2group <- final_twogroups %>% 
  group_by(samplesize, type) %>% 
  count(loo_results) %>% 
  filter(type != "freq") %>% 
  pivot_wider(names_from = "loo_results", values_from = "n") %>% 
  mutate(rate_yes = yes/iter) %>% rename(x = yes)#yes - more than 2sd 

loo_3group <- final_threegroups %>% 
  group_by(samplesize, type) %>% 
  count(loo_results) %>% 
  filter(type != "freq") %>% 
  pivot_wider(names_from = "loo_results", values_from = "n") %>% 
  mutate(rate_yes = yes/iter) %>% rename(x = yes)

waic_2group <- final_twogroups %>% 
  group_by(samplesize, type) %>% 
  count(waic_results) %>% 
  filter(type != "freq") %>% 
  pivot_wider(names_from = "waic_results", values_from = "n") %>% 
  mutate(rate_yes = yes/iter) %>% rename(x = yes)
waic_2group$x[is.na(waic_2group$x)] <- 0
waic_2group$rate_yes[is.na(waic_2group$rate_yes)] <- 0

waic_3group <- final_threegroups %>% 
  group_by(samplesize, type) %>% 
  count(waic_results) %>% 
  filter(type != "freq") %>% 
  pivot_wider(names_from = "waic_results", values_from = "n") %>% 
  mutate(rate_yes = yes/iter) %>% rename(x = yes)
waic_3group$x[is.na(waic_3group$x)] <- 0
waic_3group$rate_yes[is.na(waic_3group$rate_yes)] <- 0
```

#confidence intervals
```{r}
wald2_ci <- binom.bayes(wald_2group$x, 1000, conf.level = 0.95)
wald2_ci <- wald2_ci %>% select(-n) %>% 
  inner_join(wald_2group, by = "x")

wald3_ci <- binom.bayes(wald_3group$x, 1000, conf.level = 0.95)
wald3_ci <- wald3_ci %>% select(-n) %>% 
  inner_join(wald_3group, by = "x")

bf2_ci <- binom.bayes(bf_2group$x, 1000, conf.level = 0.95)
bf2_ci <- bf2_ci %>% select(-n) %>% 
  inner_join(bf_2group, by = "x")

bf3_ci <- binom.bayes(bf_3group$x, 1000, conf.level = 0.95)
bf3_ci <- bf3_ci %>% select(-n) %>% 
  inner_join(bf_3group, by = "x")

loo2_ci <- binom.bayes(loo_2group$x, 1000, conf.level = 0.95)
loo2_ci <- loo2_ci %>% select(-n) %>% 
  inner_join(loo_2group, by = "x")

loo3_ci <- binom.bayes(loo_3group$x, 1000, conf.level = 0.95)
loo3_ci <- loo3_ci %>% select(-n) %>% 
  inner_join(loo_3group, by = "x")

waic2_ci <- binom.bayes(waic_2group$x, 1000, conf.level = 0.95)
waic2_ci <- waic2_ci %>% select(-n) %>% 
  inner_join(waic_2group, by = "x")

waic3_ci <- binom.bayes(waic_3group$x, 1000, conf.level = 0.95)
waic3_ci <- waic3_ci %>% select(-n) %>% 
  inner_join(waic_3group, by = "x")
```



#plot by type of test
##2group
```{r}
#wald p value 
ggplot(final_twogroups, aes(x = pval)) + 
  geom_histogram(aes(y = after_stat(density)), binwidth = .05, boundary = 0) + 
  facet_grid(type ~ samplesize)  + 
  geom_vline(xintercept = .05)

plot_finaltwogroups <- final_twogroups %>% filter(type != "freq")

ggplot(plot_finaltwogroups, aes(x = bf)) + 
  geom_histogram(aes(y = after_stat(density)), binwidth = .05, boundary = 0) + 
  facet_grid(type ~ samplesize)  + 
  geom_vline(xintercept = 0)  
```
##3grp

```{r}
ggplot(final_threegroups, aes(x = pval)) + 
  geom_histogram(aes(y = after_stat(density)), binwidth = .05, boundary = 0) + 
  facet_grid(type ~ samplesize)  + 
  geom_vline(xintercept = .05)

plot_finalthreegroups <- final_threegroups %>% filter(type != "freq")

ggplot(plot_finalthreegroups, aes(x = bf)) + 
  geom_histogram(aes(y = after_stat(density)), binwidth = .05, boundary = 0) + 
  facet_grid(type ~ samplesize)  + 
  geom_vline(xintercept = 0)  
```


#plot confidence intervals 
##2groups 
```{r}
ggplot(wald2_ci, aes(x = samplesize, y = mean)) + 
  geom_line() + geom_pointrange(aes(ymin = lower, ymax = upper)) + 
  facet_wrap(vars(type)) + geom_hline(aes(yintercept = .05), linetype = "dashed")

ggplot(bf2_ci, aes(x = samplesize, y = mean)) + 
  geom_line() + geom_pointrange(aes(ymin = lower, ymax = upper)) + 
  facet_wrap(vars(type)) 

ggplot(loo2_ci, aes(x = samplesize, y = mean)) + 
  geom_line() + geom_pointrange(aes(ymin = lower, ymax = upper)) + 
  facet_wrap(vars(type)) 
ggplot(waic2_ci, aes(x = samplesize, y = mean)) + 
  geom_line() + geom_pointrange(aes(ymin = lower, ymax = upper)) + 
  facet_wrap(vars(type)) 
```
#3groups 
```{r}
ggplot(wald3_ci, aes(x = samplesize, y = mean)) + 
  geom_line() + geom_pointrange(aes(ymin = lower, ymax = upper)) + 
  facet_wrap(vars(type)) + geom_hline(aes(yintercept = .05), linetype = "dashed")

ggplot(bf3_ci, aes(x = samplesize, y = mean)) + 
  geom_line() + geom_pointrange(aes(ymin = lower, ymax = upper)) + 
  facet_wrap(vars(type)) 

ggplot(loo3_ci, aes(x = samplesize, y = mean)) + 
  geom_line() + geom_pointrange(aes(ymin = lower, ymax = upper)) + 
  facet_wrap(vars(type)) 
ggplot(waic3_ci, aes(x = samplesize, y = mean)) + 
  geom_line() + geom_pointrange(aes(ymin = lower, ymax = upper)) + 
  facet_wrap(vars(type)) 
```

#make one big plot of cis 
##2group 
```{r}
wald2_ci$test <- "wald" 
wald3_ci$test <- "wald" 

bf2_ci$test <- "bf" 
bf3_ci$test <- "bf" 

loo2_ci$test <- "loo" 
loo3_ci$test <- "loo" 
waic2_ci$test <- "waic" 
waic3_ci$test <- "waic" 
ci2 <- bind_rows(wald2_ci, bf2_ci,loo2_ci,waic2_ci)
ci3 <- bind_rows(wald3_ci, bf3_ci,loo3_ci,waic3_ci)

ggplot(ci2, aes(x = samplesize, y = mean)) + 
  geom_line() + geom_point(size = 0.2) + geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.5) + facet_grid(test ~ type) + 
  geom_hline(yintercept = .05, colour = "grey")

ggplot(ci3, aes(x = samplesize, y = mean)) + 
  geom_line() + geom_pointrange(aes(ymin = lower, ymax = upper), size = 0.2) + facet_grid(test ~ type)
```




